apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ include "myapp.fullname" . }}-db-pvc
spec:
  accessModes:
    - {{ .Values.db.persistence.accessMode }}
  resources:
    requests:
      storage: {{ .Values.db.persistence.size }}
