apiVersion: v1
kind: Secret
metadata:
  name: {{ include "myapp.fullname" . }}-db-secret
type: Opaque
stringData:
  mysql-root-password: {{ .Values.db.rootPassword | quote }}
  mysql-database: {{ .Values.db.database | quote }}
  mysql-user: {{ .Values.db.user | quote }}
  mysql-password: {{ .Values.db.password | quote }}
