apiVersion: v1
kind: Service
metadata:
  name: {{ include "myapp.fullname" . }}-db
spec:
  type: {{ .Values.db.service.type }}
  selector:
    app: {{ include "myapp.fullname" . }}-db
  ports:
    - port: {{ .Values.db.service.port }}
      targetPort: 3306
      protocol: TCP
      name: mysql
