apiVersion: v1
kind: Secret
metadata:
  name: devops-test-mysql-secret
  namespace: devops-test
type: Opaque
stringData:
  MYSQL_ROOT_PASSWORD: rootpassword
  MYSQL_USER: targets
  MYSQL_PASSWORD: password
