apiVersion: apps/v1
kind: Deployment
metadata:
  name: devops-test-mysql
  namespace: devops-test
  labels:
    app: devops-test-mysql
spec:
  replicas: 1
  selector:
    matchLabels:
      app: devops-test-mysql
  template:
    metadata:
      labels:
        app: devops-test-mysql
    spec:
      containers:
        - name: mysql
          image: mysql:latest
          imagePullPolicy: IfNotPresent
          env:
            - name: MYSQL_ROOT_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: devops-test-mysql-secret
                  key: MYSQL_ROOT_PASSWORD
            - name: MYSQL_DATABASE
              value: targets
            - name: MYSQL_USER
              valueFrom:
                secretKeyRef:
                  name: devops-test-mysql-secret
                  key: MYSQL_USER
            - name: MYSQL_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: devops-test-mysql-secret
                  key: MYSQL_PASSWORD
          ports:
            - containerPort: 3306
              name: mysql
          volumeMounts:
            - name: mysql-data
              mountPath: /var/lib/mysql
            - name: mysql-init
              mountPath: /docker-entrypoint-initdb.d
      volumes:
        - name: mysql-init
          configMap:
            name: devops-test-mysql-init
            # items optional: will map all keys as files
        - name: mysql-data
          persistentVolumeClaim:
            claimName: devops-test-mysql-pvc
