apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: devops-test-ingress
  namespace: kube-system
  annotations:
    kubernetes.io/ingress.class: nginx
    ingress.kubernetes.io/rewrite-target: /
spec:
  rules:
    - host: target.example.com
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: devops-test-web
                port:
                  number: 80
